# Generated by Django 4.0.5 on 2022-06-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_usereditprofile_facebook_usereditprofile_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereditprofile',
            name='facebook',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usereditprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usereditprofile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usereditprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
