# Generated by Django 4.0.5 on 2022-06-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_usereditprofile_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereditprofile',
            name='is_email_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
