# Generated by Django 4.0.5 on 2022-06-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('userprofile', '0005_usereditprofile_followers_usereditprofile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereditprofile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to='core.post'),
        ),
        migrations.AlterField(
            model_name='usereditprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
