# Generated by Django 4.0.5 on 2022-06-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('userprofile', '0006_usereditprofile_favourites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereditprofile',
            name='favourites',
        ),
        migrations.AddField(
            model_name='usereditprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='core.post'),
        ),
    ]
