# Generated by Django 4.0.5 on 2022-06-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='post',
            name='is_comment_disabled',
            field=models.BooleanField(default=False, help_text='Enabled by default'),
        ),
    ]
